In [3]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)    # 파이썬에서는 기본적으로 element 간 연산


[5 7 9]


In [3]:
a = np.array([1, 2, 3])
t = a + 1
print(t)    # 벡터와 스칼라의 연산 - 스칼라의 브로드캐스팅

[2 3 4]


In [4]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(x[:, 1] + y[:, 1])

[ 5 11 17]


In [8]:
print(x[:][1]) # (x[:])[1], x[:] -> [[1, 2, 3], ..., ]
print(x[1:3][1])    # (x[1:3])[1], x[1:3] -> [[4, 5, 6], [7, 8, 9]]

print(x[1:3, 1])    # 2~3행 중에 2열

[4 5 6]
[7 8 9]
[5 8]


In [13]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[20 40 60]


In [31]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a > 50
print(b)    # 브로드캐스팅

[False False False False False  True  True]


In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
a[a >= 5] = 10
a[a == 2] = -1
print(a)
print(a>=5)

a[[False, False, False, False, True, True]] = 5
print(a)

[ 1 -1  3  4 10 10]
[False False False False  True  True]
[ 1 -1  3  4  5  5]


In [77]:
import numpy as np
import random as r

a = np.random.randint(100, 201, 10)
print(a)
a[a >= 150] = 200
a[a < 150] = 100
print(a)

[181 110 175 191 182 164 151 196 135 178]
[200 100 200 200 200 200 200 200 100 200]


In [37]:
import numpy as np
import time

key = ["S", "D", "H", "C"]
deck = [1,2,3,4,5,6,7,8,9,10,"J","Q","K"]
cards = np.array([f"{i}{j}"for j in deck for i in key])
print(np.random.choice(cards, size=7, replace=False))
np.random.seed(int(time.time()))
print(np.random.choice(cards, size=7, replace=False))   # replace = False 설정 시 중복 요소 포함 x

['D8' 'CK' 'C6' 'C7' 'DJ' 'D5' 'CJ']
['C1' 'H7' 'S3' 'C6' 'H10' 'DK' 'D8']


In [36]:
a = np.array([1, 2, 3, 4, 5])
print(np.random.choice(a, size=3, replace=False))

[1 3 2]


In [57]:
import numpy as np
import random
a=[random.randint(1,16) for i in range(16)]
a=np.array(a).reshape(4,4)
print(a)
a[[3]], a[[0]] = a[[0]], a[[3]]
print(a)

print(a[3])
print(a[[3]]) # 2차원 배열의 행 교환 시 중괄호 두 개 사용에 주의

[[ 7  2 16 12]
 [ 8 13  1 14]
 [ 4 16  4  1]
 [14  3 14 10]]
[[14  3 14 10]
 [ 8 13  1 14]
 [ 4 16  4  1]
 [ 7  2 16 12]]
[ 7  2 16 12]
[[ 7  2 16 12]]
