In [4]:
import numpy as np
x = np.array([1, 3, 5])
print(x.mean())

print(np.zeros(4))
print(type(np.zeros(4)))

3.0
[0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [99]:
import numpy as np

print(np.zeros((2, 5)))
print(np.ones((2, 3)))

a = np.full((2, 3), 5) 
print(a)

a = np.eye(3)   # 정방 단위 행렬
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
import numpy as np

a = np.zeros((2, 5, 7))
# a[0][0][2] = 5
# a[0, 0, 5] = 5
print(a)

[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [62]:
import numpy as np

print(a.shape)

x = np.array([1, 3, 5, 6]).reshape(2, 2)   # 전체 크기 맞아야 reshape 가능
print(x)
print(type(x))
print(x.reshape(1, 4))

print(a.reshape(2, 35))

(2, 5, 7)
[[1 3]
 [5 6]]
<class 'numpy.ndarray'>
[[1 3 5 6]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
import numpy as np

print(np.array([i for i in range(0, 100) if i % 3 == 1]).reshape(3, 11))

[[ 1  4  7 10 13 16 19 22 25 28 31]
 [34 37 40 43 46 49 52 55 58 61 64]
 [67 70 73 76 79 82 85 88 91 94 97]]


In [4]:
list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:][1])
print(list1[:, 1])

[2, 12]


TypeError: list indices must be integers or slices, not tuple

In [78]:
import numpy as np

list1 = [[1, 11], [2, 12], [3, 13]]
np_array = np.array(list1)
print(np_array)
print(np_array[:, 1])
print(np_array[1, :])
print(np_array[1:, 1:])

[[ 1 11]
 [ 2 12]
 [ 3 13]]
[11 12 13]
[ 2 12]
[[12]
 [13]]


In [88]:
import numpy as np

a = np.array([i for i in range(0,20)]).reshape(4,5)
print(a[1:3, 2:4])

print(a)

[[ 7  8]
 [12 13]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [102]:
import math
math.sqrt(2)

import numpy as np
np.sqrt([2, 3, 4])  # 모든 원소에 적용

a = np.array([2, 3, 4])
print(np.sqrt(a))

print(list(map(np.sqrt, a)))

[1.41421356 1.73205081 2.        ]
[1.4142135623730951, 1.7320508075688772, 2.0]


In [3]:
import numpy as np 

ary = np.array([[1, 2], [3, 4], [5, 6]])
# print(ary)
# print(ary.transpose())

ary = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 2, 2)
print(ary)
print(ary.transpose())  
# 각 요소 기준으로 따지면 (0, 1, 1) 위치에 있는 요소가 (1, 1, 0) 위치로 이동
# transpose(2, 0, 1)인 경우 (2, 3, 4) 위치에 있는 요소가 (4, 2, 3) 위치로 이동

ary = np.array([1, 2, 3])
print(ary.transpose())


ary = np.array([[[1, 2], [2, 3]], [[3, 4], [4, 5]], [[5, 6], [6, 7]]])
print(ary.shape)

print(np.transpose(ary, (2, 0, 1)).shape) # 기존 axis: 0, 1, 2에 매핑 -> 2, 0, 1로 axis 변경 (설정x 시 2, 1, 0으로 변경)
# https://pybasall.tistory.com/124

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
[1 2 3]
(3, 2, 2)
(2, 3, 2)
