## 50

In [25]:
import numpy as np

a = np.array([np.random.randint(16) for i in range(16)]).reshape(4, 4)
print(a)
a[0], a[-1] = a[-1], a[0]
print(a)


[[ 9 12 10  5]
 [10  5 11  6]
 [ 0  3 14  5]
 [12  5 12 12]]
[[12  5 12 12]
 [10  5 11  6]
 [ 0  3 14  5]
 [12  5 12 12]]


In [34]:
import numpy as np
print(np.zeros((5,6),int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [42]:
import numpy as np

a = np.array([[9, 4, 6], [1, 5, 2], [3, 0, 7]])
a = np.sort(a)
print(np.sort(a, axis = 0))

[[0 2 5]
 [1 3 7]
 [4 6 9]]
