In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(np.mean(a))
print(np.mean([1, 2, 3]))

[1 2 3]
2.0
2.0


In [61]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [29]:
a = np.ones([2, 3])
print(a)
b = np.zeros([2, 3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
a = [[1, 11], [2, 12], [3, 13]]
print(a[:][1])

b = np.array(a)
print(b[:, 1])

[2, 12]
[11 12 13]


In [38]:
import math

print(math.sqrt([2, 3, 4]))

TypeError: must be real number, not list

In [42]:
print(np.sqrt([2, 3, 4]))

a = np.array([2, 3, 4])
print(np.sqrt(a))

[1.41421356 1.73205081 2.        ]
[1.41421356 1.73205081 2.        ]


In [49]:
print(np.zeros(3))
print(np.zeros([4, 3]))
print(np.zeros(5))

a = np.zeros([5, 3])
a += 4
print(a)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [66]:
a = np.array([[1, 2, 3], [4, 5, 6]])


print(a)
print(a.transpose())
print(np.transpose(a))



a = np.array([i for i in range(1, 61)]).reshape(3, 4, 5)
print(a)
print(a.transpose())    # 면, 행, 열 -> 열, 행, 면

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


In [70]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [85]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1])
print(a[:, 1])

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(x[:, 1] + y[:, 1])

a = np.array([10, 20, 30, 40, 50, 60, 70])
i = [1, 3, 5]
print(a[i])

[4 5 6]
[2 5 8]
[ 5 11 17]
[20 40 60]


In [88]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
print(a > 50)

[False False False False False  True  True]


In [111]:
print(np.random.random(5))
print(np.random.rand(5))
print(np.random.randint(10))    # 한계 설정
print(np.random.randn(5))

[0.7305511  0.52767073 0.537099   0.06198804 0.08979004]
[0.8740294  0.77850203 0.27974361 0.3623119  0.85744576]
0
[ 0.92525039 -0.55726307 -0.72628109  1.61972035  1.70394219]


In [117]:
print(np.linspace(0, 12, 4))
print(np.linspace(0, 12, 4, retstep=True))
print(np.linspace(0, 12, 4, endpoint=False))

[ 0.  4.  8. 12.]
(array([ 0.,  4.,  8., 12.]), 4.0)
[0. 3. 6. 9.]


In [3]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

(3,)
