In [2]:
import numpy as np

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
a = np.arange(10, 100, 10)
print(a[a > 50])

[60 70 80 90]


In [57]:
print(np.random.randint(0, 10, [2, 3]))
print(np.random.rand())
print(np.random.random())

print(np.random.random(5))
print(np.random.rand(5))


# random과 rand의 차이

[[0 6 0]
 [4 4 7]]
0.4342984242063834
0.6533238779320678
[0.25919949 0.91641812 0.42551715 0.29144912 0.36746989]
[0.66901755 0.72054827 0.62334619 0.24954628 0.5526268 ]


In [81]:
a = np.arange(1, 50, 6)
np.random.choice(a, 5, replace=False)

array([43,  1, 49, 13, 25])

In [84]:
a = np.random.randint(1, 17, (4, 4))
print(a)
a[[0]], a[[3]] = a[[3]], a[[0]] # 다차원 배열의 행 교환
print(a)

[[14  4  2 16]
 [10  4  6  3]
 [16 12  6  5]
 [ 5  9 16 11]]
[[ 5  9 16 11]
 [10  4  6  3]
 [16 12  6  5]
 [14  4  2 16]]
