# 과제 numpy

### 8번
참고</br>
element-wise: 원소 별</br>
complex number: 복소수</br>
</br>
파이썬에서 복소수 표현:</br>
i 대신 j 또는 J 붙임 → ex) 2 + 3j</br>
실수부, 허수부 구분해 표현 → ex) complex(2, 3)</br>


In [51]:
import numpy as np

a = np.array([1 + 1j, 1 + 2j, 1.1, 2, 3.3])
print("주어진 배열:", a)
print("복소수 검사:", np.iscomplex(a))
print("실수 검사:", np.isreal(a))
print("스칼라 검사:", [np.isscalar(i) for i in a])

주어진 배열: [1. +1.j 1. +2.j 1.1+0.j 2. +0.j 3.3+0.j]
복소수 검사: [ True  True False False False]
실수 검사: [False False  True  True  True]
스칼라 검사: [True, True, True, True, True]


### 18번
참고</br>
standard-normal-distribution: 표준정규분포</br>
</br>

In [52]:
import numpy as np

print(np.random.standard_normal(15))

[-0.42058306 -0.31979753 -0.72832716 -0.90844314  1.43863092  0.08179337
  1.01757746 -1.50174377 -0.36396635  2.36305934  1.97763026  1.39790717
 -0.03372578  1.12042127 -0.49011276]


### 28번

In [53]:
import numpy as np

a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 38번
참고</br>
numpy배열.tobytes(): 배열 -> 바이트 변환</br>
np.frombuffer(바꾸고 싶은 bytes , dtype = <자료형>): 바이트 -> 배열 변환

In [54]:
import numpy as np

a = np.array([1, 2, 3])
print("주어진 배열:", a)
aBytes = a.tobytes()
print("바이트 변환:", aBytes)
aArr = np.frombuffer(aBytes, dtype = a.dtype)
print("배열 변환:", aArr)

주어진 배열: [1 2 3]
바이트 변환: b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
배열 변환: [1 2 3]


### 48번
참고</br>
평균 μ, 표준편차 σ 를 갖는 정규분포 N(μ, σ^2)의 난수 생성:</br>
np.random.normal(μ, σ, size)

In [50]:
import numpy as np

print(np.random.normal(200, np.sqrt(7), (8, 5)))

[[197.33540411 200.9546746  200.28091351 194.28712339 195.74905102]
 [199.78876027 203.57344043 200.66155989 192.88337861 202.17626792]
 [199.69673826 195.6651827  194.79097232 200.39310977 206.02221298]
 [194.64752057 196.11107991 196.21478442 198.41140423 194.58727988]
 [199.91540936 198.35516108 201.5168902  200.79520594 198.43877024]
 [199.55793151 201.14406651 200.34989095 201.93681941 201.8295112 ]
 [201.17420209 201.4967266  203.67443868 201.79143117 200.98865332]
 [199.60849805 198.14451838 199.8946535  200.69540144 199.66274609]]


### 58번

In [4]:
import numpy as np

a = np.array([i for i in range(1, 10)]).reshape(3, 3)
print("주어진 배열:")
print(a)
print("바뀐 배열:")
print(a[::-1,::-1])

주어진 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
바뀐 배열:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
