## 강의자료

In [1]:
import numpy as np

In [19]:
print(np.zeros(5))
print(np.mean([1, 2, 3, 4, 5])) # numpy 배열이 아닌 경우에도 평균 계산 가능

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)  # 1차원 배열 - (열,)
print(a.mean())

a = np.array([1, 2, 3, 4]).reshape(1, 4)
print(a.shape)
print(a.mean())

a = np.array([[2], [1], [3]])
print(a.shape)

[0. 0. 0. 0. 0.]
3.0
(6,)
3.5
(1, 4)
2.5
(3, 1)


In [23]:
x = np.ones((3, 4), int)
print(x)
print(x.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)


In [43]:
x = np.array(np.arange(1, 21)).reshape(4, 5)
# np.array(1, 10, 0.1) 형태로 arange에는 간격 설정 가능
print(x)
print(x[:][3])  # x[:]의 [3] 원소 -> x 전체에서 4번째 원소
print(x[:, 1])  # x[:, 1] -> 전체 행, 두번째 열에 해당되는 모든 원소
print(x[:, 1:2])
print(x[1:5:2, 2:4])  # 2에서 5행(2스텝), 3에서 4열에 해당되는 모든 원소
print(x[1, 1])
x

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[16 17 18 19 20]
[ 2  7 12 17]
[[ 2]
 [ 7]
 [12]
 [17]]
[[ 8  9]
 [18 19]]
7


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [63]:
import math

print(math.sqrt(2))
# math.sqrt([2, 4, 9])

print(np.sqrt(2))
print(np.sqrt([4, 9, 16]))

1.4142135623730951
1.4142135623730951
[2. 3. 4.]


In [68]:
x = np.zeros([4, 3])
print(x)
x[1:3, 1] = 1
x += 3
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[3. 3. 3.]
 [3. 4. 3.]
 [3. 4. 3.]
 [3. 3. 3.]]


In [72]:
a = np.array([[1, 2],[3, 4]])
print(a)
print(a.transpose())

print(np.transpose([[1, 2],[3, 4]])) # 파이썬 리스트에 사용

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [35]:
x = range(10)
y = np.array([i for i in range(0, 20, 2)])
print(x)
print(y)
print(x + y)    # 원소 개수 같아야 가능

range(0, 10)
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18 21 24 27]


In [41]:
a = np.array([i * 10 for i in range(1, 8)])
print(a)

print(a[[1, 3, 5]])
# print(a[(1, 3, 5)])   # 여러 인덱스 한번에 접근 시 반드시 리스트 사용

i = [1, 2]
print(a[i])


[10 20 30 40 50 60 70]
[20 40 60]
[20 30]


In [100]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a[1:6:2]
print(type(b))
print(b)
b[1] = 10
print(b)
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
[20 40 60]
[20 10 60]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [103]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
print(a > 50)
print(a[a > 50])

[False False False False False  True  True]
[60 70]


In [48]:
import random

print(random.random())
print(np.random.rand())
print(np.random.rand(5))

print(random.randint(1, 5)) # 1..5
print(np.random.randint(1, 5, (2, 3)))  # 1 until 5

# randint, random, standard_normal -> 크기를 하나의 인자로 지정(다차원인 경우 튜플로)
# rand, randn -> 크기를 인자 여러개로 지정
print(np.random.random((2, 3)))
# np.random.random(2, 3)
# np.random.rand((2, 3))
print(np.random.rand(2, 3))

0.09065563406058086
0.7510616097374673
[0.65758374 0.72053807 0.13377249 0.96140987 0.00719683]
5
[[2 4 1]
 [3 3 2]]
[[0.44295546 0.23655933 0.12813898]
 [0.48696661 0.88596522 0.27945423]]
[[0.37437469 0.6120566  0.21372031]
 [0.13559354 0.71467985 0.61181528]]


In [357]:
a = np.random.random(5)
print(a)
print(np.all(a > 0.3))
print(np.any(a > 0.8))

[0.48988931 0.11581322 0.98653417 0.24410205 0.26626813]
False
True


In [368]:
print(np.linspace(0, 12, 2, dtype=int))
print(np.linspace(0, 12, 4, retstep=True))  # 간격 출력
print(np.linspace(0, 12, 4, endpoint=False))

[ 0 12]
(array([ 0.,  4.,  8., 12.]), 4.0)
[0. 3. 6. 9.]


In [50]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

## 수업내용

In [2]:
import numpy as np

In [52]:
a = np.full([2, 3], 4)
print(a)

[[4 4 4]
 [4 4 4]]


In [15]:
a = np.eye(3)   # 정방 단위 행렬
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
print(a.shape)

(2, 2)


In [54]:
a = np.array([1, 2, 3, 4, 5])
np.random.choice(a, 3, replace=False)

array([4, 2, 3])

In [4]:
a = np.random.randint(1, 17, (4, 4))
print(a)
a[[0]], a[[3]] = a[[3]], a[[0]]
print(a)

[[14 14  6  2]
 [ 7 16  8  6]
 [14  3 13 14]
 [ 8  3  7 12]]
[[ 8  3  7 12]
 [ 7 16  8  6]
 [14  3 13 14]
 [14 14  6  2]]
