## 강의자료

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display

In [4]:
print(pd.Series([7, 3, 6, 8]))

x = pd.Series([7, 3, 6, 8], ['서울', '대구', '부산', '광주'])
print(x)
print(list(x))  # 리스트로 변환 시 값 리스트
print(x['서울'])
print(x[['서울', '대구']])

0    7
1    3
2    6
3    8
dtype: int64
서울    7
대구    3
부산    6
광주    8
dtype: int64
[7, 3, 6, 8]
7
서울    7
대구    3
dtype: int64


In [28]:
print(x.index)
print(x.values)

Index(['서울', '대구', '부산', '광주'], dtype='object')
[7 3 6 8]


In [5]:
print(x[sorted(x.index)])
print(x.sort_index())
print(x.reindex(sorted(x.index)))
print(x)

print(x[sorted(x.index, key=lambda a: x[a])])
print(x.sort_values())

광주    8
대구    3
부산    6
서울    7
dtype: int64
광주    8
대구    3
부산    6
서울    7
dtype: int64
광주    8
대구    3
부산    6
서울    7
dtype: int64
서울    7
대구    3
부산    6
광주    8
dtype: int64
대구    3
부산    6
서울    7
광주    8
dtype: int64
대구    3
부산    6
서울    7
광주    8
dtype: int64


In [42]:
# numpy 배열은 인덱스 수 맞지 않는 경우 더할 수 없었음
# pandas에서는 일치하는 인덱스 없는 경우 NaN
x = pd.Series([3, 8, 5, 9], ['서울', '대구', '부산', '광주'])
y = pd.Series([2, 4, 5, 1], ['대구', '부산', '서울', '대전'])

print(x + y)    # 결과 인덱스의 순서는 정렬된 순서

광주     NaN
대구    10.0
대전     NaN
부산     9.0
서울     8.0
dtype: float64


In [47]:
x = pd.Series([1, 2, 1, 1, 2, 3, 4])
print(x.unique())

[1 2 3 4]


In [52]:
age = {'민준':23, '현우':43, '서연':12, '동현':45}
p = pd.Series(age)
print(p)

민준    23
현우    43
서연    12
동현    45
dtype: int64


In [55]:
print(p[2:3])
print(p[1])

서연    12
dtype: int64
43


In [7]:
data = {'age': [23, 43, 12, 45],
    'name': ['민준', '현우', '서연', '동현'],
    'height': [1123, 123, 123, 112]}
p = pd.DataFrame(data, index = [1, 2, 3, 4])
display(p)

age name  height
1   23   민준    1123
2   43   현우     123
3   12   서연     123
4   45   동현     112

In [8]:
print(p.iloc[2])   # 컬럼명이 인덱스가 되어 Series로 반환됨
print(p.loc[2])
print(p.iloc[:, -1])

print(p['age'])
print(p.age)

# 출력 결과의 Name: 출력되는 인덱스 또는 컬럼 이름

age        12
name       서연
height    123
Name: 3, dtype: object
age        43
name       현우
height    123
Name: 2, dtype: object
1    1123
2     123
3     123
4     112
Name: height, dtype: int64
1    23
2    43
3    12
4    45
Name: age, dtype: int64
1    23
2    43
3    12
4    45
Name: age, dtype: int64


In [13]:
display(p.head(2))
display(p.tail(3))

age name  height
1   23   민준    1123
2   43   현우     123

age name  height
2   43   현우     123
3   12   서연     123
4   45   동현     112

In [9]:
a = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
p = pd.DataFrame(a, columns=["First", "Second"])

print(p.Second[[True, True, False, False, True]])

0     2
1     4
4    10
Name: Second, dtype: int64


In [96]:
display(p)
print(p.mean())
print(p.mean(1))

First  Second
0      1       2
1      3       4
2      5       6
3      7       8
4      9      10

First     5.0
Second    6.0
dtype: float64
0    1.5
1    3.5
2    5.5
3    7.5
4    9.5
dtype: float64


In [105]:
a = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
p = pd.DataFrame(a, columns=['수온', '상온'])

display(p)
p.astype(float)

수온  상온
0   1   2
1   3   4
2   5   6
3   7   8
4   9  10

수온    상온
0  1.0   2.0
1  3.0   4.0
2  5.0   6.0
3  7.0   8.0
4  9.0  10.0

## 수업내용

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display

In [17]:
x = pd.Series(np.arange(10, 20, 2), index = ['서울', '부산', '광주', '대전', '대구'])
print(x)

y = x.reindex(['부산', '광주', '서울', '용인', '대전'])
print(y)  # NaN이 추가되면서 타입이 실수형으로 바뀜
# print(y.astype(int))    # NaN은 정수형으로 나타낼 수 없음

서울    10
부산    12
광주    14
대전    16
대구    18
dtype: int32
부산    12.0
광주    14.0
서울    10.0
용인     NaN
대전    16.0
dtype: float64


In [13]:
x = pd.Series([1, 2, 3, 4])
print(x.values)
print(type(x.values))   # numpy 배열로 반환됨, 인덱스는 x

print(x.index > 1)
print(x.values > 2)
print(x[x.values > 2])

[1 2 3 4]
<class 'numpy.ndarray'>
[False False  True  True]
[False False  True  True]
2    3
3    4
dtype: int64


In [14]:
x = pd.Series([7, 3, 6, 8], ['서울', '대구', '부산', '광주'])
print(x.index + "a") # Index 객체에도 연산 브로드캐스트 가능

Index(['서울a', '대구a', '부산a', '광주a'], dtype='object')


In [50]:
# 요약: 인덱스에 대한 bfill, ffill은 사전순으로 적용되는 것

print("----1----")
x = pd.Series([1, 2, 3, 4], ['a', 'b', 'c', 'd'])   # 인덱스는 사전순이어야(사전순이 아니면 method 적용 불가)
print(x.reindex(['e', 'b', 'a', 'e'], method='bfill')) # NaN 그대로
# 문자 인덱스 'e'의 경우 뒷 인덱스와 값이 존재하지 않기 때문에 NaN 유지
print(x.reindex(['e', 'b', 'a', 'e', 'f'], method='ffill')) # ffill, pad: 앞 인덱스에 해당하는 value 가져옴
# 문자 인덱스 'e'인 경우 앞 인덱스 'd'의 값을 가져오므로 4가 들어가게됨

print("----2----") 
print(x.reindex(['g', 'a', 'b', 'c', 'd', 'e', 'f'], method='ffill'))  # 이전 인덱스의 값 가져옴

----1----
e    NaN
b    2.0
a    1.0
e    NaN
dtype: float64
e    4
b    2
a    1
e    4
f    4
dtype: int64
----2----
g    4
a    1
b    2
c    3
d    4
e    4
f    4
dtype: int64


In [16]:
print("----3----")
x = pd.Series([8, 2, 3, 4], ['aa', 'bb', 'dd', 'ee'])   # 인덱스가 사전 순이 아닌 경우 오류 발생
print(x.reindex(['sdf', 'aa', 'bb', 'cc', 'dd', 'ee', 'sd']))
print(x.reindex(['sdf', 'aa', 'bb', 'cc', 'dd', 'ee', 'sd'], method="ffill"))   # 사전 순으로 "sdf" 앞의 가장 가까운 인덱스는 "ee"이므로 ee의 값 불러옴

print("----4----")
x = pd.Series(['a', 'b', 'c', 'd'], [2, 6, 7, 8])
print(x)
x.reindex(np.arange(0, 9), method="ffill")

# 인덱스 0일 때의 ffill -> NaN
# 값이 정해진 마지막 인덱스 이후에 대한 ffill -> NaN

----3----
sdf    NaN
aa     8.0
bb     2.0
cc     NaN
dd     3.0
ee     4.0
sd     NaN
dtype: float64
sdf    4
aa     8
bb     2
cc     2
dd     3
ee     4
sd     4
dtype: int64
----4----
2    a
6    b
7    c
8    d
dtype: object


0    NaN
1    NaN
2      a
3      a
4      a
5      a
6      b
7      c
8      d
dtype: object

In [3]:
x = pd.DataFrame([[1, 2, 3], [2, 3, 4], [4, 5, 6]], [1, 2, 3], columns=['a', 'b', 'c'])
# 2차원 배열 -> 각 행이 행이됨
display(x)

display(x.iloc[0:2, 0:2])

a  b  c
1  1  2  3
2  2  3  4
3  4  5  6

a  b
1  1  2
2  2  3

In [5]:
data = {'age' : [23, 43, 12, 45], 'name' : ['민준', '현우', '서연', '동현']
# 딕셔너리 -> 각 항의 키가 컬럼명, 값이 컬럼이 됨
, 'height' : [175.3, 180.3, 165.8, 172.7]}
x = pd.DataFrame(data, index=[1, 2, 3, 4])
x

age name  height
1   23   민준   175.3
2   43   현우   180.3
3   12   서연   165.8
4   45   동현   172.7

In [6]:
x[['age', 'name']]

age name
1   23   민준
2   43   현우
3   12   서연
4   45   동현

In [7]:
print(x[x.age > 30])   # x.age의 결과가 numpy배열이기 때문에 가능
print(x.age > 30)
print(x[[True, True, False, True]]) # boolean 배열 - 인덱스에 대해 적용

   age name  height
2   43   현우   180.3
4   45   동현   172.7
1    False
2     True
3    False
4     True
Name: age, dtype: bool
   age name  height
1   23   민준   175.3
2   43   현우   180.3
4   45   동현   172.7


In [96]:
print(x.mean())
print(x.mean(1))

age        30.750
height    173.525
dtype: float64
1     99.15
2    111.65
3     88.90
4    108.85
dtype: float64


In [101]:
x = pd.Series(['php', 'python', 'java', 'c#'], [1, 2, 3, 4])
x.apply(lambda a: a.upper())    # 제작한 함수 apply 이용해 값 대상 브로드캐스트 가능

1       PHP
2    PYTHON
3      JAVA
4        C#
dtype: object

In [119]:
a = pd.Series([1, 2, 3, 4, 5])
print(a)
a.drop(0)   # 저장 x
a = a.drop(0)
print(a)

# a = np.arange(5)  # numpy 배열에는 drop 없음
# print(a.drop(0))

0    1
1    2
2    3
3    4
4    5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64
